### ISSUE TITLE
Cannot reboot my switch after copy these file

### ISSUE THREAD

**Issue by callmedragon1008** [o0Zz/sys-con#8] opened 2024-06-09 10:56 UTC
Panic occurred while  running atmosphere.

Title ID: 690000000000000D
Error: std::abort (...)

**Comment by BigBoss320** [comment] 2024-06-09 12:46
What's your version of the switch firmware?
I have the same issue while booting on atmosphere with Sys-Con v1.1.0.
But using v1.0.0 works.
You probably have to update your Switch to v18.0.0+ and Atmosphere to the latest.
I am using sys-con v1.0.0 because it supports switch v17.0.1 (that i am currently using).
Sys-con 1.0.1+ is for switch v18.0 (as i understand) 
I haven't tested it but i hope that i found a way to patch your problem!

**Comment by o0Zz** [comment] 2024-06-09 13:29
Could you please provide the logs after the crash in order to understand where come from the problem.
 @BigBoss320 Sys-con 1.1.0 also works with older switch version. Sys-con rely on libnx which is compatible with a wide range of firmware version. Thus you can use 1.1.0 instead of 1.0.0 even for switch 17.x

**Comment by BigBoss320** [comment] 2024-06-09 13:42
Oh okay, didn't know about it. I can then provide the crash report (it may be the same?)
Where can I found it (I've never did it before)?

**Comment by callmedragon1008** [comment] 2024-06-09 14:26
I don't see any log.log file in \config\sys-con folder. The version 1.0.0 work for me. But 1.1.0 doesn't.

**Comment by BigBoss320** [comment] 2024-06-09 14:30
In my switch i am on atmosphere 1.6.2, maybe we have to update it ?

**Comment by callmedragon1008** [comment] 2024-06-09 15:06
I am at 1.6.2 too. But I don't want to update it. Firmware v18 still unstable.

**Comment by o0Zz** [comment] 2024-06-09 15:15
@BigBoss320 everything is in the documentation: https://github.com/o0Zz/sys-con?tab=readme-ov-file#logs.
@callmedragon1008 there is few user that use FW 17, here for exemple: #4  and it seems to work. I'm not sure the issue is meet is caused by the FW v17 itself. Could you try to manually create a log.log to see if you have more logs ?

**Comment by BigBoss320** [comment] 2024-06-09 17:26
can't generate logs, even by creating an empty file. i used all possible log_level

**Comment by o0Zz** [comment] 2024-06-09 18:42
@texita Could you confirm your console is running FW 17 too ?
I'm trying to figure out if we need 2 different build for this issue (one for FW 17 and one for FW 18). I means, from your logs I was able to see you ran sys-con v1.1.0 on FW 17. Could you confirm ? Anything special on your console ? @BigBoss320 seems not be able to run this binary (v1.1.0) on its console, however according to the description the module seems to fail during initialization phase (Before the first log). Unfortunatly my switch is already running FW18 thus I can't test easily. On the other hand, MissionControl https://github.com/ndeadly/MissionControl/releases seems to support FW18 on his last version and inform users that this one will not run on previous FW version while it was the case before. Thus, is there any breaking change between FW17 and FW18 ? Thank you for your help

**Comment by texita** [comment] 2024-06-09 18:49
I'm on fw 17.0.1 and atmosphere 1.7.0.
If you read the description it say that thay added support for 18.0.0 ofw, but you MUST use atmosphere 1.7.0.
Anyway i'm using mission control 0.11. but if you want i can try sys-con without it, not a problem for me.

**Comment by texita** [comment] 2024-06-09 18:51
> I am at 1.6.2 too. But I don't want to update it. Firmware v18 still unstable.

Update atmopshere to 1.7.0, not the firmware

**Comment by o0Zz** [comment] 2024-06-09 19:50
Ok thank you for your help. So Atmophere 1_7_0 is requiered for sys-con 1.1.0. I will edit the release to inform this dependency

**Comment by o0Zz** [comment] 2024-06-09 19:56
@callmedragon1008 @BigBoss320  try these binaries and let me know if it works on your side. That the latest build linked with Atmosphere 1.7 and 1.6. Select the one compatible with your console

[sys-con-1.1.0+10-ATMOSPHERE-1_6_2.zip](https://github.com/user-attachments/files/15754022/sys-con-1.1.0%2B10-ATMOSPHERE-1_6_2.zip)
[sys-con-1.1.0+10-ATMOSPHERE-1_7_0.zip](https://github.com/user-attachments/files/15754023/sys-con-1.1.0%2B10-ATMOSPHERE-1_7_0.zip)

**Comment by BigBoss320** [comment] 2024-06-09 20:00
this build works for me (ams 1.6.2, ofw 17.0.1)

**Comment by BigBoss320** [comment] 2024-06-09 20:06
i can't test it, i haven't a compatible controller. PDP xBox one cotroller aren't recognized

**Comment by o0Zz** [comment] 2024-06-09 20:12
Did you check the logs ? xbox one controller are supported, it should miss your vid/pid in the configuration. Check for the logs and documentation.

**Comment by BigBoss320** [comment] 2024-06-09 20:20
wich option should i use for logs ?

**Comment by BigBoss320** [comment] 2024-06-09 20:55
but this problem i a known issue with PDP xbox controllers. I have a Series and a One controller from PDP, both not working/responding

**Comment by callmedragon1008** [comment] 2024-06-10 02:59
sys-con-1.1.0+10-ATMOSPHERE-1_6_2 work for me. sys-con-1.1.0+10-ATMOSPHERE-1_7_0 doesn't, it show the "Panic occurred while running atmosphere." when i reboot.

**Comment by o0Zz** [comment] 2024-06-10 06:46
@BigBoss320 yes open a new issue please for this issue. Usually, you have to add your controller in the config.ini

Typically, add:

```
[0e6f-02de]
driver=xboxone
```

or 

```
[0e6f-02de]
driver=xbox360
```

**Comment by o0Zz** [comment] 2024-06-10 06:47
@callmedragon1008 ok thus this issue is closed in this case. In the next version I will build 1 version for atmosphere 1.6 and 1 version for atmosphere 1.7 in order to let user with atmosphere 1.6 use this submodule

**Closed by o0Zz** 2024-06-10 06:47 UTC
Labels: bug

**Comment by o0Zz** [comment] 2024-06-14 07:11
FYI the latest build support multiple AMS version (Thus it should fix your issue) ->https://github.com/o0Zz/sys-con/releases/
